PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT COUNT(?uri)
   WHERE
   {
       GRAPH <MUSUEM_URI>
       {
           ?uri a crm:E39_Actor;
                rdfs:label ?name;
                skos:exactMatch ?lod_identifier.
           ?lod_identifier skos:inScheme <http://vocab.getty.edu/ulan>.
           
           ?uri crm:P92i_was_brought_into_existence_by ?o1.
           ?o1 crm:P4_has_time-span ?o2.
           ?o2 crm:P82a_begin_of_the_begin ?byear.
       }
   } limit 100