PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX schema: <http://schema.org/>

SELECT ?lod_identifier ?lod_label ?lod_source
WHERE {
<PARENT_URI> a crm:E39_Actor ;
  skos:exactMatch ?lod_identifier.
OPTIONAL {
  ?lod_identifier skos:preflabel ?lod_label.
}
OPTIONAL {
  ?lod_identifier skos:inScheme ?lod_source.
}

}