PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
SELECT ?uri ?name ?byear
    WHERE 
    { 
          GRAPH <http://data.americanartcollaborative.org/npg>
          {
            ?uri a crm:E39_Actor;
                 crm:P131_is_identified_by ?o1.
            ?o1 rdfs:label ?name.
            
            ?uri crm:P98i_was_born ?o2.
            ?o2 crm:P4_has_time-span ?b.
            ?b crm:P82_at_some_time_within ?byear.
        }
    }